- name: Clone Arch-Update repository
  git:
    repo: https://github.com/Antiz96/arch-update.git
    dest: /tmp

- name: Build and install Arch-Update using makepkg
  command: >
    makepkg -si --noconfirm
    chdir=/tmp/arch-update/
  become: true
