- name: Konsave - Install from git repository on pipx isolated environment
  community.general.pipx:
    name: konsave
    source: git+https://github.com/Prayag2/konsave.git

- name: Konsave - Importing "{{ item.name }}" profile
  become: true
  become_user: "{{ item.user }}"
  shell: pipx run konsave -i "{{ item.path }}"
  with_items: "{{ Network_Shares }}"

- name: Konsave - Applying "{{ item.name }}" profile
  become: true
  become_user: "{{ item.user }}"
  shell: pipx run konsave -a "{{ item.name }}"
  with_items: "{{ Network_Shares }}"
