- name: Konsave - Install from git repository on pipx isolated environment
  community.general.pipx:
    name: konsave
    source: git+https://github.com/Prayag2/konsave.git

- name: Konsave - Importing Etienne profile
  become: true
  become_user: etienne
  shell: pipx run konsave -i /mnt/TrueNAS/IT/Ansible/Etienne.knsv

- name: Konsave - Applying Etienne profile
  become: true
  become_user: etienne
  shell: pipx run konsave -a Etienne
