- name: Users_Faces - Copy users faces to /var/lib/AccountsService/icons/
  ansible.builtin.copy:
    src: /mnt/TrueNAS/IT/Ansible/Users_Faces/{{ item.name }}
    dest: /var/lib/AccountsService/icons/{{ item.name }}
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ users }}"

- name: Users_Faces - Creating Users session file
  ansible.builtin.file:
    path: /var/lib/AccountsService/users/{{ item.name }}
    owner: root
    group: root
    mode: '0644'
    state: touch
  with_items: "{{ users }}"

- name: Users_Faces - Linking users session to icon
  ansible.builtin.copy:
    dest: /var/lib/AccountsService/users/{{ item.name }}
    content: |
      [User]
      Session=
      PasswordHint=
      Icon=/var/lib/AccountsService/icons/{{ item.name }}
      SystemAccount=false
  with_items: "{{ users }}"
